name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      pypi_repo: 
        default: "testpypi"
      
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip build virtualenv twine
        sudo apt-get update && sudo apt-get install -y libgirepository1.0-dev
    - name: Build
      run: |
        python -m build
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/*.whl
    - name: Install and test
      run: |
        virtualenv --clear venv
        . venv/bin/activate
        python -m pip install dist/*.whl
        python test/test.py
        
  publish_if_tagged:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - name: Get build artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pip }}
      run: |
        python -m twine upload --repository ${{ inputs.pypi_repo || 'testpypi' }} *.whl
